name: Tests

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Windows VS2022, os: windows-2022 }
          - { name: Linux GCC, os: ubuntu-latest }
          - { name: macOS, os: macos-latest }
          - {
              name: Android,
              os: ubuntu-latest,
              flags: "-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21",
            }
          - {
              name: iOS,
              os: macos-latest,
              flags: "-G Xcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_ARCHITECTURES=arm64",
            }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Linux Dependencies
        if: runner.os == 'Linux' && matrix.platform.name != 'Android'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          build-essential git make pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
          libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
          libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
          libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
          libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev

      - name: Configure
        run: cmake -B build ${{matrix.platform.flags}} -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Create iOS IPA
        if: matrix.platform.name == 'iOS'
        run: |
          mkdir -p Payload
          cp -r build/bin/Connect4.app Payload/
          zip -r Connect4.ipa Payload

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Connect4-${{ matrix.platform.name }}
          path: |
            build/bin/
            *.ipa
